version: '3.8'

  services:
    nginx:
      image: nginx:latest
      ports:
        -80:80
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - htdocs:/var/www/html
      depends_on:
        - php
      restart: always

    php:
      build: ./php
      volumes:
        - ./htdocs:/var/www/html

    mysql:

    phpmyadmin:

volumes:
  db:data:
